export const newsList = [
  {
    key: 0,
    title: "케이펫페어 대구",
    img: "KpetDegu24.jpg",
    desc: "입장료: 10,000원 | 사전등록 무료 | 3일간 진행",
    position: "엑스코 동관 4,5홀",
    time: "10:00 ~ 18:00(입장마감 17:30)",
    homepage:
      "https://k-pet.co.kr/introduction/scheduled_exhibition/24pet_exco_info/",
    startDate: "24.09.27",
    endDate: "24.09.29",
    location: "대구 엑스코",
    from: "케이펫페어",
    acceptUrl: "https://k-pet.co.kr/member-daegu/?c=JOIN&a=EsMemberAgree",
  },
  {
    key: 1,
    title: "케이펫페어 일산",
    img: "KpetIllsan24.jpg",
    desc: "입장료: 12,000원 | 1차 사전등록 무료 | 3일간 진행",
    position: "킨텍스 1전시장 전관",
    time: "09:30~18:00 (입장마감 17:30)",
    homepage: "https://k-pet.co.kr/introduction/scheduled_exhibition/24pet_k2/",
    startDate: "24.11.15",
    endDate: "24.11.17",
    location: "일산 킨텍스",
    from: "케이펫페어",
    acceptUrl: "https://megazoo.co.kr/member/?c=JOIN&a=EsMemberAgree",
  },
  {
    key: 2,
    title: "케이펫페어 서울",
    img: "KpetpairSeoul24.jpg",
    desc: "입장료: 10,000원 | 사전등록 무료 | 3일간 진행",
    position: "코엑스 D홀(2호선 삼성역, 9호선 봉은사역)",
    time: "10:00 ~ 18:00(입장마감 17:30)",
    homepage: "https://k-pet.co.kr/introduction/scheduled_exhibition/24pet_co/",
    startDate: "24.08.23",
    endDate: "24.08.25",
    location: "서울 코엑스",
    from: "케이펫페어",
    acceptUrl: "",
  },
];
